version: '3.8'
services:
  db:
    image: postgres:16.0-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=instagram_scraping_db
    ports:
      - '15432:5432'
#    volumes:
#      - db:/var/lib/postgresql/data
#      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
#volumes:
#  db:
#    driver: local
